# YOLOv5s with EfficientNet-B7 backbone - Multi-Scale Version

# Parameters
nc: 80 # number of classes
depth_multiple: 0.33 # model depth multiple
width_multiple: 0.50 # layer channel multiple

# Anchors
anchors:
  - [10, 13, 16, 30, 33, 23] # P3/8
  - [30, 61, 62, 45, 59, 119] # P4/16
  - [116, 90, 156, 198, 373, 326] # P5/32

# EfficientNet-B7 backbone with proper feature level handling
backbone:
  # [from, number, module, args]
  [
    [-1, 1, EfficientNetB7Adapter, [False]], # 0: Main adapter (P5 - 512, 20x20)
    [-1, 1, EfficientNetP4Adapter, []], # 1: P4 features (256, 40x40)
    [-1, 1, EfficientNetP3Adapter, []], # 2: P3 features (128, 80x80)
    [0, 1, SPPF, [512, 5]], # 3: Enhance P5 features
  ]

# YOLOv5s head
head:
  # Build FPN top-down pathway (P5 -> P4 -> P3)
  [
    [-1, 1, Conv, [256, 1, 1]], # 4: Reduce P5 channels
    [-1, 1, nn.Upsample, [None, 2, "nearest"]], # 5: Upsample to P4 size
    [[1, -1], 1, Concat, [1]], # 6: Concat with P4 features
    [-1, 1, C3, [256, False]], # 7: Process P4 features

    [-1, 1, Conv, [128, 1, 1]], # 8: Reduce channels
    [-1, 1, nn.Upsample, [None, 2, "nearest"]], # 9: Upsample to P3 size
    [[2, -1], 1, Concat, [1]], # 10: Concat with P3 features
    [-1, 1, C3, [128, False]], # 11: Process P3 features (small)

    # Build bottom-up pathway (P3 -> P4 -> P5)
    [-1, 1, Conv, [128, 3, 2]], # 12: Downsample P3->P4
    [[7, -1], 1, Concat, [1]], # 13: Concat with P4 features
    [-1, 1, C3, [256, False]], # 14: Process P4 features (medium)

    [-1, 1, Conv, [256, 3, 2]], # 15: Downsample P4->P5
    [[3, -1], 1, Concat, [1]], # 16: Concat with enhanced P5
    [-1, 1, C3, [512, False]], # 17: Process P5 features (large)

    # Detection head
    [[11, 14, 17], 1, Detect, [nc, anchors]], # 18: Detect(P3, P4, P5)
  ]
